### ISSUE TITLE
Invalid Json Tests fail despite being correctly invalid

### ISSUE THREAD

**Issue by p-rintz** [networktocode/schema-enforcer#103]
### Environment
* Python version: 3.8.5
* schema-enforcer version:  develop-branch

### Expected Behavior
Schema Invalid tests pass by failing the same.

### Observed Behavior
Schema Invalid tests fail.

This is because the jsonschema __results_ arent being cleared between running the valid tests and the invalid tests.
This leads to _results_sorted_ and _expected_results_sorted_ being different, as the previous pass of the valid test is still being included in the results.

**results_sorted:**
`[{'instance_location': '/home/philipp/Documents/public/schema-enforcer/schema/tests/test/valid', 'instance_name': 'full_implementation.json', 'instance_type': 'TEST', 'result': 'PASS', 'schema_id': 'schemas/test'}, {'absolute_path': [...], 'message': "123 is not of type 'string'", 'result': 'FAIL', 'schema_id': 'schemas/test'}]`

**expected_results_sorted:**
`[{'absolute_path': [...], 'message': "123 is not of type 'string'", 'result': 'FAIL', 'schema_id': 'schemas/test'}]`

### Steps to Reproduce
1. Have Json File to be validated.
2. Have a valid test in the subfolder tests/*/valid/
3. Have invalid tests in the tests/*/invalid/ subfolder.
4. Generate the expected results for the invalid tests.
5. Run schema-enforcer schema --check

I first saw this on production data, also the same on the following testdata:
```
schema
├── schemas
│   └── test.yml
└── tests
    └── test
        ├── invalid
        │   ├── invalid_type1
        │   │   ├── data.json
        │   │   └── results.yml
        │   └── invalid_type2
        │       ├── data.json
        │       └── results.yml
        └── valid
            └── full_implementation.json
```

**cat schema/schemas/test.yml** 
```
---
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/test"
description: "NFTables Firewall Configuration schema."
type: "object"
properties:
  firewall:
    type: "object"
    uniqueItems: true
    additionalProperties: false
    required:
      - "rule"
      - "variables"
    properties:
      rule:
        type: "object"
        properties:
          bool:
            type: "boolean"
          Text:
            type: "string"
          dict:
            type: "object"
      variables:
        type: "object"
```

**cat schema/tests/test/invalid/invalid_type1/data.json** 
```
{
    "firewall": {
        "rule": {
            "bool": "true",
            "Text": "text",
            "dict": {
            }
        },
        "variables": {
            "Text": "text",
            "array": [
            ]
        }
    }
}
```

**cat schema/tests/test/invalid/invalid_type2/data.json** 
```
{
    "firewall": {
        "rule": {
            "bool": true,
            "Text": 123,
            "dict": {
            }
        },
        "variables": {
            "Text": "text",
            "array": {
            }
        }
    }
}
```

**cat test.json**
```
{
    "firewall": {
        "rule": {
            "bool": true,
            "Text": "text",
            "dict": {
            }
        },
        "variables": {
            "Text": "text",
            "array": [
            ]
        }
    }
}
```

The following patch fixes the issue for me:
```
diff --git a/schema_enforcer/schemas/manager.py b/schema_enforcer/schemas/manager.py
index e34b4fd..9658e80 100644
--- a/schema_enforcer/schemas/manager.py
+++ b/schema_enforcer/schemas/manager.py
@@ -201,6 +201,7 @@ class SchemaManager:
         test_dirs = next(os.walk(invalid_test_dir))[1]
 
         results = []
+        schema.clear_results()
         for test_dir in test_dirs:
             data_file = find_file(os.path.join(invalid_test_dir, test_dir, "data"))
             expected_results_file = find_file(os.path.join(invalid_test_dir, test_dir, "results"))
```

**Comment by p-rintz** [comment]
It seems that the same problem happens during the generation of the (invalid) results files.
The __results_ in the _generate_invalid_tests_expected_ function weren't being cleared, so the previously generated results were being prepended to the following results.
Clearing the __results_ in the generation, and thus removing the additional expected false "failures" from the results.yml also makes the above patch no longer work, as the _expected_results_ are no longer duplicated (I was wondering why they were when I was looking at the code earlier today...). The __results_ need to be cleared after each invalid test, which this now does:

```
diff --git a/schema_enforcer/schemas/manager.py b/schema_enforcer/schemas/manager.py
index e34b4fd..8bfd37f 100644
--- a/schema_enforcer/schemas/manager.py
+++ b/schema_enforcer/schemas/manager.py
@@ -202,6 +202,7 @@ class SchemaManager:
 
         results = []
         for test_dir in test_dirs:
+            schema.clear_results()
             data_file = find_file(os.path.join(invalid_test_dir, test_dir, "data"))
             expected_results_file = find_file(os.path.join(invalid_test_dir, test_dir, "results"))
 
@@ -264,6 +265,7 @@ class SchemaManager:
         # For each test, load the data file, test the data against the schema and save the results
         for test_dir in test_dirs:
 
+            schema.clear_results()
             data_file = find_file(os.path.join(invalid_test_dir, test_dir, "data"))
 
             if not data_file:
```

**Comment by p-rintz** [comment]
This is issue before the patch:

The invalid_type1 result does not have the 123 is not a string problem in the data.json and just gets this appended from the other invalid test.

**cat schema/tests/test/invalid/invalid_type1/results.yml**
```
---
results:
  - result: "FAIL"
    schema_id: "schemas/test"
    absolute_path:
      - "firewall"
      - "rule"
      - "Text"
    message: "123 is not of type 'string'"
  - result: "FAIL"
    schema_id: "schemas/test"
    absolute_path:
      - "firewall"
      - "rule"
      - "bool"
    message: "'true' is not of type 'boolean'"
```
**cat schema/tests/test/invalid/invalid_type2/results.yml** 
```
---
results:
  - result: "FAIL"
    schema_id: "schemas/test"
    absolute_path:
      - "firewall"
      - "rule"
      - "Text"
    message: "123 is not of type 'string'"
```
