### ISSUE TITLE
Provide automatic mapping of top level properties

### ISSUE THREAD

**Issue by PhillSimonds** [networktocode/schema-enforcer#47]
This issue has been opened to acquire input on the propositions it makes.

Right now, in order to map a structured data file to the schema definition it should adhere to a user has to add a decorator to the structured data file or configure a `[tool.schema_enforcer.schema_mapping]` section in the pyproject.toml file.

It may be beneficial to have the tool automatically infer the top level property in a file and, if a schema is defined with the same top level property, use that schema to check structured data files for adherence to schema. For instance, given the following structured data file and the subsequent schema definition, we could have the tool automatically map the top level key of `dns_servers` in the structured data file to the top level key of `dns_servers` in the schema definition and automatically check for data adherence to schema. This **could** be beneficial as it would provide schema validation capabilities without requiring the user to define a mapping. I believe this was implemented in a previous iteration of the tool per my read of some of the original documentation, but was subsequently removed.

```yaml
dns_servers:
  - address: 192.168.1.2
  - address: 192.168.1.3
```

```yaml
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/dns_servers"
description: "DNS Server Configuration schema."
type: "object"
properties:
  dns_servers:
    type: "array"
    items:
      type: "object"
      properties:
        name:
          type: "string"
        address:
... output omitted for brevity
```

The way structured data files are currently mapped to schemas, if both a decorator defining the mapping exists and a `schema_mapping` section in a pyproject.toml file is defined, the definitions in both locations will be used to validate the schema. It may be a good idea to specify that only one of three methods is used to map the schema with the following rules of precedence:

1) if a decorator exists, use the mapping in the decorator.
2) if a mapping exists in the pyproject.toml file exists, and a decorator **does not** exist, use the mapping
3) If neither a decorator exists nor a mapping exists in the pyproject.toml file, use the default method of automatically mapping the top level property of a structured data file to the top level property of an schema definition
4) If none of the above mappings exist, do not validate the file. In such cases the `schema-enforcer --show-checks` command should show that no checks will be performed for the structured data file.

If we opt to implement the tool in this way, it may be beneficial to add a flag which could make structured data files with top level properties that map a given schema exempt from validation checks. This could be beneficial if someone needs to override the default.
