### ISSUE TITLE
JSON Schema "format" property is ignored

### ISSUE THREAD

**Issue by progala** [networktocode/schema-enforcer#94]
### Environment
* Python version:  3.7.10
* schema-enforcer version:  1.0.1

### Expected Behavior

Given below schema:

```yaml
root@598fbf392820:/local# cat schema/schemas/dns.yml
---
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/dns_servers"
description: "DNS Server Configuration schema."
type: "object"
properties:
  dns_servers:
    type: "array"
    items:
      type: "object"
      properties:
        name:
          type: "string"
        address:
          type: "string"
          format: "ipv4"
        vrf:
          type: "string"
        date:
          type: "string"
          format: "date"
      required:
        - "address"
      uniqueItems: true
required:
  - "dns_servers"
```

The below data should fail validation due to the incorrect format of IP address:

```yaml
root@598fbf392820:/local# cat rtr-01-jpn/dns.yml
# jsonschema: schemas/dns_servers
---
dns_servers:
  - address: "10.5.1.256"
  - address: "10.2.2.2"
```
### Observed Behavior

Schema validation passes:

```
❯ schema-enforcer validate --show-pass
PASS | [FILE] ./rtr-01-jpn/dns.yml
ALL SCHEMA VALIDATION CHECKS PASSED
```

### Steps to Reproduce

1. Create schema and data files from "Expected Behaviour" section.
2. Run `schema-enforcer validate` in directory containing schema and data files
