### ISSUE TITLE
Schema validation passed even if invalid schema is defined

### ISSUE THREAD

**Issue by lvrfrc87** [networktocode/schema-enforcer#97]
### Environment
Python version: Python 3.9.1
schema-enforcer version: 1.0.1

### Expected Behavior
Not sure if is an expected behavior from jsonschema library or something related to schema-enforcer.

When defined an invalid jsonschem, schema -enforcer returns anyway `ALL SCHEMA VALIDATION CHECKS PASSED`

That makes bit tricky to understand if and what is wrong with the jsonschema definition

Fake json schema:

```
---
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/checks"
description: "Schema Checks"
type: "object"
properties:
  type: "integer"
  items:
    type: "object"
    properties:
      name: bla bla bla bla
```

Correct json schema:
```
---
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/checks"
description: "Schema Checks"
type: "object"
properties:
  checks:
    type: "array"
    items:
      type: "object"
      properties:
        name:
          type: "string"
```

In both cases, the correct file is picked up

```
(root_venv) olivierif:cu-pretzels-networking-checks olivierif$ schema-enforcer validate --show-checks | grep checks
.//run_pre_change_checks.yml                       []
./group_vars/all/checks.yml                        ['schemas/checks']
```

**Comment by chipn** [comment]
@dgarros @PhillSimonds

What's the desired behavior for a bad schema? 

One possible solution:
1. Run check_if_valid for all schemas when loading
2. If any results fail for a schema, print an error and skip adding the schema to the SchemaManager.

This behavior would at least give the user a warning about a bad schema and not give the impression that everything is ok.

```
11:18 $ schema-enforcer validate --show-checks
ERROR: File invalid.yml is not a valid jsonschema.
Structured Data File                               Schema ID
--------------------------------------------------------------------------------
./hostvars/chi-beijing-rt1/dns.yml                 ['schemas/dns_servers']
./hostvars/chi-beijing-rt1/syslog.yml              []
./hostvars/eng-london-rt1/dns.yaml                 []
./hostvars/eng-london-rt1/ntp.yaml                 ['schemas/ntp']
```

```
11:19 $ cat schema/schemas/invalid.yml
---
$schema: "http://json-schema.org/draft-07/schema#"
$id: "schemas/checks"
description: "Schema Checks"
type: "object"
properties:
  type: "integer"
  items:
    type: "object"
    properties:
      name: bla bla bla bla
```
